FROM ubuntu:18.04

RUN apt-get update && apt-get install -y -q --no-install-recommends \
	pulseaudio \
	socat \
	sox \
	alsa-utils

RUN apt-get install -y -q --no-install-recommends \
	make \
	portaudio19-dev

# ENV USER_DOCKER=pigeolian
# RUN useradd -m ${USER_DOCKER}
# RUN gpasswd -a ${USER_DOCKER} sudo
# USER ${USER_DOCKER}

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
      alsa-utils \
      libasound2 \
      libasound2-plugins \
      pulseaudio \
      pulseaudio-utils \
      python3.7-minimal \
      python3-setuptools \
      python3-pip \
      mplayer \
      mpv

ENV HOME /home/pulseaudio
RUN useradd --create-home --home-dir $HOME pulseaudio \
    && usermod -aG audio,pulse,pulse-access pulseaudio \
    && chown -R pulseaudio:pulseaudio $HOME

COPY config/asound.conf /etc/asound.conf
COPY config/pulseaudio.client.conf /tmp

#USER root
WORKDIR /work
CMD ["/bin/bash"]