FROM ubuntu:20.04

RUN apt-get update && apt-get install -y -q --no-install-recommends \
	pulseaudio \
	make

RUN apt-get update && apt-get install -y -q --no-install-recommends \
	alsa-utils

WORKDIR /work
USER root
CMD ["/bin/bash"]